name: Trigger auto deployment for containerapptest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerapptest-AutoDeployTrigger-5903a63b-05f7-441a-9198-c920fbd545f6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINERAPPTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTEST_REGISTRY_PASSWORD }}
          containerAppName: containerapptest
          resourceGroup: POC_OU_SK_TEST
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


